# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1517, 1146)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonStation1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStation1.setGeometry(QtCore.QRect(250, 550, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStation1.setFont(font)
        self.pushButtonStation1.setObjectName("pushButtonStation1")
        self.pushButtonStation2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStation2.setGeometry(QtCore.QRect(250, 362, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStation2.setFont(font)
        self.pushButtonStation2.setObjectName("pushButtonStation2")
        self.pushButtonStation3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStation3.setGeometry(QtCore.QRect(250, 175, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStation3.setFont(font)
        self.pushButtonStation3.setObjectName("pushButtonStation3")
        self.pushButtonStation6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStation6.setGeometry(QtCore.QRect(690, 550, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStation6.setFont(font)
        self.pushButtonStation6.setObjectName("pushButtonStation6")
        self.pushButtonStation4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStation4.setGeometry(QtCore.QRect(690, 175, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStation4.setFont(font)
        self.pushButtonStation4.setObjectName("pushButtonStation4")
        self.pushButtonStation5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStation5.setGeometry(QtCore.QRect(690, 362, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStation5.setFont(font)
        self.pushButtonStation5.setObjectName("pushButtonStation5")
        self.pushButtonHomeBase = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHomeBase.setGeometry(QtCore.QRect(440, 1010, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonHomeBase.setFont(font)
        self.pushButtonHomeBase.setObjectName("pushButtonHomeBase")
        self.labelDesiredDeliveries = QtWidgets.QLabel(self.centralwidget)
        self.labelDesiredDeliveries.setGeometry(QtCore.QRect(1090, 30, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelDesiredDeliveries.setFont(font)
        self.labelDesiredDeliveries.setObjectName("labelDesiredDeliveries")
        self.pushButtonStopDeliveries = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStopDeliveries.setGeometry(QtCore.QRect(1090, 1010, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStopDeliveries.setFont(font)
        self.pushButtonStopDeliveries.setObjectName("pushButtonStopDeliveries")
        self.pushButtonStartDeliveries = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStartDeliveries.setGeometry(QtCore.QRect(1090, 900, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonStartDeliveries.setFont(font)
        self.pushButtonStartDeliveries.setObjectName("pushButtonStartDeliveries")
        self.labelLiveUpdates = QtWidgets.QLabel(self.centralwidget)
        self.labelLiveUpdates.setGeometry(QtCore.QRect(1090, 400, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelLiveUpdates.setFont(font)
        self.labelLiveUpdates.setObjectName("labelLiveUpdates")
        
        self.pushButtonRemoveStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRemoveStop.setGeometry(QtCore.QRect(1090, 360, 185, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonRemoveStop.setFont(font)
        self.pushButtonRemoveStop.setObjectName("pushRemoveStation")
        
        self.pushButtonClearStops = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClearStops.setGeometry(QtCore.QRect(1307, 360, 185, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonClearStops.setFont(font)
        self.pushButtonClearStops.setObjectName("pushClearStops")

        
        
        self.labelPlantLayout = QtWidgets.QLabel(self.centralwidget)
        self.labelPlantLayout.setGeometry(QtCore.QRect(10, 10, 1071, 1171))
        self.labelPlantLayout.setText("")
        self.labelPlantLayout.setPixmap(QtGui.QPixmap(":/newPrefix/plantLayout.png"))
        self.labelPlantLayout.setObjectName("labelPlantLayout")
        self.labelPlantLayout.raise_()
        self.pushButtonStation1.raise_()
        self.pushButtonStation2.raise_()
        self.pushButtonStation3.raise_()
        self.pushButtonStation6.raise_()
        self.pushButtonStation4.raise_()
        self.pushButtonStation5.raise_()
        self.pushButtonHomeBase.raise_()
        self.labelDesiredDeliveries.raise_()
        self.pushButtonStopDeliveries.raise_()
        self.pushButtonStartDeliveries.raise_()
        self.labelLiveUpdates.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1517, 21))
        self.menubar.setObjectName("menubar")
        self.menuManufacturing_Plant_Deliveries = QtWidgets.QMenu(self.menubar)
        self.menuManufacturing_Plant_Deliveries.setObjectName("menuManufacturing_Plant_Deliveries")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuManufacturing_Plant_Deliveries.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonStation1.setText(_translate("MainWindow", "Station 1"))
        self.pushButtonStation2.setText(_translate("MainWindow", "Station 2"))
        self.pushButtonStation3.setText(_translate("MainWindow", "Station 3"))
        self.pushButtonStation6.setText(_translate("MainWindow", "Station 6"))
        self.pushButtonStation4.setText(_translate("MainWindow", "Station 4"))
        self.pushButtonStation5.setText(_translate("MainWindow", "Station 5"))
        self.pushButtonHomeBase.setText(_translate("MainWindow", "Home Base"))
        self.labelDesiredDeliveries.setText(_translate("MainWindow", "Desired Deliveries:"))
        self.pushButtonStopDeliveries.setText(_translate("MainWindow", "STOP"))
        self.pushButtonStartDeliveries.setText(_translate("MainWindow", "Start Deliveries"))
        self.labelLiveUpdates.setText(_translate("MainWindow", "Live Updates:"))
        self.menuManufacturing_Plant_Deliveries.setTitle(_translate("MainWindow", "Manufacturing Plant Deliveries"))
        
    
import test_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

